#!/bin/bash
# daily-memory-demo.sh

echo "═══════════════════════════════════════════════════════════"
echo "     PAI Daily Memory Injection - Live Demo"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "This demo shows how PAI remembers context across sessions"
echo "inspired by Clawdbot's Seneca assistant."
echo ""
echo "─────────────────────────────────────────────────────────"
echo "Step 1: Manual Hook Execution"
echo "─────────────────────────────────────────────────────────"
echo ""

# Get the project root (parent of docs/)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
cd "$PROJECT_ROOT"

export PAI_DIR="$PROJECT_ROOT/.claude"
.claude/hooks/load-daily-memory.ts
echo ""
echo "─────────────────────────────────────────────────────────"
echo "Step 2: What Memory Was Loaded?"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "✓ Last 2 sessions from History/Sessions/"
echo "✓ Last 3 learnings from History/Learnings/"
echo "✓ Today's work from History/*/$(date +%Y-%m-%d)*"
echo ""
echo "─────────────────────────────────────────────────────────"
echo "Step 3: Session Continuity Test"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "Starting new Claude Code session with daily memory..."
echo "Try asking: 'What have we been working on recently?'"
echo ""
echo "PAI should reference recent sessions and learnings"
echo "WITHOUT you having to explain the context!"
echo ""
echo "═══════════════════════════════════════════════════════════"
